CREATE DATABASE IF NOT EXISTS rednorte_db;
CREATE DATABASE IF NOT EXISTS pacientes_db;
CREATE DATABASE IF NOT EXISTS citas_db;
CREATE DATABASE IF NOT EXISTS espera_db;
CREATE DATABASE IF NOT EXISTS notificaciones_db;